### ISSUE TITLE
你好 我有个问题

### ISSUE THREAD

**Issue by dnslin** [linpinger/foxbook-golang#1]
我在Google上搜罗了一圈只看到你这边有用java写 equb转 mobi的程序
我想问一下你用的什么依赖 能发一下吗（maven？） 亚马逊那个已经不提供下载了

**Comment by linpinger** [comment]
java 版的epub转mobi，还是调用了kindlegen来进行转换

现在能找到的，能跨平台转为azw3的，还是go语言版的库: github.com/leotaku/mobi，这是实际测试下来相对好的一个库

**Comment by dnslin** [comment]
嗯 我找到kindlegen了
